src/3. EndPoint/Readify.EndPoint.UI_MVC/Components/Book/BookViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Readify.Domain.Core.Book.Services;

namespace Readify.EndPoint.UI_MVC.Components.Book
{
    public class BookViewComponent(IBookService bookService) : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var books = bookService.GetRecentlyBooks(5);
            return View("Books", books);
        }
    }
}

src/3. EndPoint/Readify.EndPoint.UI_MVC/Components/Category/CategoryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Readify.Domain.Core.Category.Services;

namespace Readify.EndPoint.UI_MVC.Components.Category
{
    public class CategoryViewComponent(ICategoryService categoryService) : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var categories = categoryService.GetPopularCategories(5);
            return View("Categories", categories);
        }
    }
}

src/3. EndPoint/Readify.EndPoint.UI_MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Readify.EndPoint.UI_MVC.Models;
using System.Diagnostics;

namespace Readify.EndPoint.UI_MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/3. EndPoint/Readify.EndPoint.UI_MVC/Views/Home/Index.cshtml
@model CategoryBookViewModel

@{
    ViewData["Title"] = "صفحه اصلی";
}

<section class="hero">
    <h1>هر کتابی که می‌خواهی، اینجا هست</h1>
    <p>با پیش از صدها عنوان کتاب در دسته‌بندی‌های متفاوت، سفر شگفت‌انگیز خود را آغاز کنید</p>
    <button>مشاهده پرفروش‌ترین ها</button>
</section>

<div class="container">

    @await Component.InvokeAsync("Category");
    
    @await Component.InvokeAsync("Book");




</div>